### ISSUE TITLE
"cannot send more responses than requests" if connection is reset mid transfer

### ISSUE THREAD

**Issue by ariscop** [webbit/webbit#120]
version 0.4.15
Steps to reproduce:

createWebServer(i)
    .add(new StaticFileHandler([path])
    .start().get();

curl [url] | dd of=/dev/null bs=[smaller than file size] count=1

**Comment by zhegexiaohuozi** [comment]
Waiting for fix

**Comment by frankyen389** [comment]
I have the same issue, how should I do?

10:02:48,122 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) org.webbitserver.WebbitException: cannot send more responses than requests on [id: 0xdd66ffce, /192.168.251.35:12019 :> /172.17.4.172:8082]
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.WebbitException.fromException(WebbitException.java:36)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java:171)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpChannelHandler$3.run(NettyHttpChannelHandler.java:94)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10:02:48,123 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.lang.Thread.run(Thread.java:745)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) Caused by: java.lang.IllegalStateException: cannot send more responses than requests
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(HttpContentEncoder.java:100)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.Channels.write(Channels.java:704)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.Channels.write(Channels.java:671)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.write(NettyHttpResponse.java:208)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.flushResponse(NettyHttpResponse.java:196)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java:169)
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	... 8 more
10:02:48,124 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) org.webbitserver.WebbitException: cannot send more responses than requests on [id: 0xdd66ffce, /192.168.251.35:12019 :> /172.17.4.172:8082]
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.WebbitException.fromException(WebbitException.java:36)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java:171)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpChannelHandler$3.run(NettyHttpChannelHandler.java:94)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10:02:48,125 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.lang.Thread.run(Thread.java:745)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) Caused by: java.lang.IllegalStateException: cannot send more responses than requests
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(HttpContentEncoder.java:100)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.Channels.write(Channels.java:704)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.Channels.write(Channels.java:671)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.write(NettyHttpResponse.java:208)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.flushResponse(NettyHttpResponse.java:196)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java:169)
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	... 8 more
10:02:48,126 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) org.webbitserver.WebbitException: cannot send more responses than requests on [id: 0xdd66ffce, /192.168.251.35:12019 :> /172.17.4.172:8082]
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.WebbitException.fromException(WebbitException.java:36)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java:171)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at org.webbitserver.netty.NettyHttpChannelHandler$3.run(NettyHttpChannelHandler.java:94)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
10:02:48,127 ERROR [stderr] (WEBBIT-HANDLER-THREAD-4-1-thread) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

**Comment by ariscop** [comment]
It's been over a year since there was a commit to master, webbit seems pretty dead

**Comment by gabereiser** [comment]
This issue is with netty and can easily be fixed in your own fork: https://github.com/webbit/webbit/blob/master/src/main/java/org/webbitserver/netty/NettyHttpChannelHandler.java

Webbit is dead, there are no new commits and pull requests are ignored.  The source code is there so it's pretty much self-support right now.

**Comment by RedShift1** [comment]
Same problem occurs when sending a few newlines.

**Comment by DefinitlyEvil** [comment]
i got it too!

**Comment by Arisstath** [comment]
Still getting this issue, it doesn't seem that anything is breaking though.

**Comment by RedShift1** [comment]
I switched to Undertow (http://undertow.io/) if there are people here still searching an alternative.

**Comment by DefinitlyEvil** [comment]
@RedShift1 thanks good to know!
